# Spanner-Alembic issue reproduction

This repo reproduces the issue we've encountered when using Cloud Spanner and Alembic: [Migrations drop and identically recreate certain foreign keys #271 ](https://github.com/googleapis/python-spanner-sqlalchemy/issues/271)

The demo uses a local [Cloud Spanner emulator](https://cloud.google.com/spanner/docs/emulator), that you will need to setup.

The [second commit](https://github.com/jstlaurent/spanner-alembic-fk-issue/commit/3c6c84e50d17390e9690a6d8314753b8f3f376c1) show the initial models and migration generated by running the following commands:
```shell
cd migrations
alembic -n demo revision --autogenerate -m 'initial_generation'
alembic -n demo upgrade head
```

The [third commit](https://github.com/jstlaurent/spanner-alembic-fk-issue/commit/e1ef95b03985e5d935e498bf1695a2cdf9cdaf43) updates a model and generates a new migration, by running the following command:
```shell
alembic -n demo revision --autogenerate -m 'field_update'
```
This migration deletes and recreates existing foreign keys, even if these fields have not be modified:
```python
with op.batch_alter_table('link', schema=None) as batch_op:
    batch_op.drop_constraint('fk_1', type_='foreignkey')
    batch_op.drop_constraint('fk_2', type_='foreignkey')
    batch_op.create_foreign_key('fk_1', 'a', ['environment_id', 'a_id'], ['environment_id', 'id'])
    batch_op.create_foreign_key('fk_2', 'b', ['environment_id', 'b_id'], ['environment_id', 'id'])
```

You can replicate the issue by modifying a model in `demo/models.py` and running Alembic to create a new revision.
